exercicio1a:
	gcc -o exercicio1a exercicio1a.c -lm

exercicio1b:
	gcc -o exercicio1b exercicio1b.c -lm

exercicio1c:
	gcc -o exercicio1c exercicio1c.c -lm

exercicio1d:
	gcc -o exercicio1d exercicio1d.c -lm

exercicio2a:
	gcc -o exercicio2a exercicio2a.c -lm

exercicio2b:
	gcc -o exercicio2b exercicio2b.c -lm

exercicio2c:
	gcc -o exercicio2c exercicio2c.c listaEncadeada.c -lm





